DWAPlannerROS:
  # max_vel_x: 0.5
  # min_vel_x: 0.1
  # max_vel_y: 0.0
  # min_vel_y: 0.0
  # max_rotational_vel: 1.0
  # min_rotational_vel: 0.1
  # acc_lim_x: 2.0
  # acc_lim_y: 0.0
  # acc_lim_theta: 3.2
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1